python  ./pwb.py transferbot -lang:zh -tolang:zh -tofamily:speedydeletion  -family:wikipedia "-catr:条目删除候选"
python  ./pwb.py transferbot -lang:it -tolang:it -tofamily:speedydeletion  -family:wikipedia "-catr:Pagine in cancellazione per argomento"
python  ./pwb.py transferbot -lang:co -tolang:co -tofamily:speedydeletion  -family:wikipedia "-catr:Da supprimà"
python  ./pwb.py transferbot -lang:es -tolang:es -tofamily:speedydeletion  -family:wikipedia "-catr:Wikipedia:Consultas de borrado"
python  ./pwb.py transferbot -lang:ru -tolang:ru -tofamily:speedydeletion  -family:wikipedia "-catr:Википедия:Кандидаты на удаление"
python  ./pwb.py transferbot -lang:ro -tolang:ro -tofamily:speedydeletion  -family:wikipedia "-catr:Pagini de șters"
python  ./pwb.py transferbot -lang:nl -tolang:nl -tofamily:speedydeletion  -family:wikipedia "-catr:Wikipedia:Pagina weg"
python  ./pwb.py transferbot -lang:wa -tolang:wa -tofamily:speedydeletion  -family:wikipedia "-catr:Pådjes a disfacer"
python  ./pwb.py transferbot -lang:pt -tolang:pt -tofamily:speedydeletion  -family:wikipedia "-catr:!Páginas para eliminar"
python  ./pwb.py transferbot -lang:nap -tolang:nap -tofamily:speedydeletion  -family:wikipedia "-catr:Paggene 'a scancellà"
python  ./pwb.py transferbot -lang:yi -tolang:yi -tofamily:speedydeletion  -family:wikipedia "-catr:געשטעלטע צו מעקן"
python  ./pwb.py transferbot -lang:fr -tolang:fr -tofamily:speedydeletion  -family:wikipedia "-catr:Page proposée à la suppression"
python  ./pwb.py transferbot -lang:de -tolang:de -tofamily:speedydeletion  -family:wikipedia "-catr:Wikipedia:Löschkandidat"
python  ./pwb.py transferbot -lang:fa -tolang:fa -tofamily:speedydeletion  -family:wikipedia "-catr:مقاله‌های نامزد حذف"
python  ./pwb.py transferbot -lang:ja -tolang:ja -tofamily:speedydeletion  -family:wikipedia "-catr:削除依頼中のページ"
python  ./pwb.py transferbot -lang:sq -tolang:sq -tofamily:speedydeletion  -family:wikipedia "-catr:Faqe për grisje"
python  ./pwb.py transferbot -lang:sv -tolang:sv -tofamily:speedydeletion  -family:wikipedia "-catr:Sidor föreslagna för radering"
python  ./pwb.py transferbot -lang:ur -tolang:ur -tofamily:speedydeletion  -family:wikipedia "-catr:مضامین برائے حذف"
python  ./pwb.py transferbot -lang:uk -tolang:uk -tofamily:speedydeletion  -family:wikipedia "-catr:Статті-кандидати на вилучення"
python  ./pwb.py transferbot -lang:diq -tolang:diq -tofamily:speedydeletion  -family:wikipedia "-catr:Bestere"
python  ./pwb.py transferbot -lang:el -tolang:el -tofamily:speedydeletion  -family:wikipedia "-catr:Σελίδες για γρήγορη διαγραφή"
python  ./pwb.py transferbot -lang:zh -tolang:zh -tofamily:speedydeletion  -family:wikipedia "-catr:快速删除候选"
python  ./pwb.py transferbot -lang:ug -tolang:ug -tofamily:speedydeletion  -family:wikipedia "-catr:Candidates for speedy deletion"
python  ./pwb.py transferbot -lang:vi -tolang:vi -tofamily:speedydeletion  -family:wikipedia "-catr:Chờ xóa"
python  ./pwb.py transferbot -lang:ca -tolang:ca -tofamily:speedydeletion  -family:wikipedia "-catr:Sol·licituds de supressió immediata"
python  ./pwb.py transferbot -lang:mdf -tolang:mdf -tofamily:speedydeletion  -family:wikipedia "-catr:Candidates for speedy deletion"
python  ./pwb.py transferbot -lang:it -tolang:it -tofamily:speedydeletion  -family:wikipedia "-catr:Cancellare subito"
python  ./pwb.py transferbot -lang:ar -tolang:ar -tofamily:speedydeletion  -family:wikipedia "-catr:صفحات للحذف السريع"
python  ./pwb.py transferbot -lang:id -tolang:id -tofamily:speedydeletion  -family:wikipedia "-catr:Artikel yang layak untuk dihapus"
python  ./pwb.py transferbot -lang:es -tolang:es -tofamily:speedydeletion  -family:wikipedia "-catr:Wikipedia:Borrar \(definitivo\)"
python  ./pwb.py transferbot -lang:ru -tolang:ru -tofamily:speedydeletion  -family:wikipedia "-catr:Википедия:К быстрому удалению"
python  ./pwb.py transferbot -lang:ro -tolang:ro -tofamily:speedydeletion  -family:wikipedia "-catr:Pagini de șters rapid"
python  ./pwb.py transferbot -lang:nl -tolang:nl -tofamily:speedydeletion  -family:wikipedia "-catr:Wikipedia:Nuweg"
python  ./pwb.py transferbot -lang:pt -tolang:pt -tofamily:speedydeletion  -family:wikipedia "-catr:!Páginas para eliminação rápida"
python  ./pwb.py transferbot -lang:no -tolang:no -tofamily:speedydeletion  -family:wikipedia "-catr:Sider som er foreslått raskt slettet"
python  ./pwb.py transferbot -lang:lo -tolang:lo -tofamily:speedydeletion  -family:wikipedia "-catr:Candidates for speedy deletion"
python  ./pwb.py transferbot -lang:nah -tolang:nah -tofamily:speedydeletion  -family:wikipedia "-catr:Huiquipedia:Borrar \(definitivo\)"
python  ./pwb.py transferbot -lang:tr -tolang:tr -tofamily:speedydeletion  -family:wikipedia "-catr:Vikipedi silinecek sayfalar"
python  ./pwb.py transferbot -lang:tl -tolang:tl -tofamily:speedydeletion  -family:wikipedia "-catr:Mga pahinang mabilisang buburahin"
python  ./pwb.py transferbot -lang:bjn -tolang:bjn -tofamily:speedydeletion  -family:wikipedia "-catr:Artikal nang layak hagan dihapus"
python  ./pwb.py transferbot -lang:new -tolang:new -tofamily:speedydeletion  -family:wikipedia "-catr:Candidates for speedy deletion"
python  ./pwb.py transferbot -lang:sah -tolang:sah -tofamily:speedydeletion  -family:wikipedia "-catr:Бикипиэдьийэ:Түргэнник соторго"
python  ./pwb.py transferbot -lang:war -tolang:war -tofamily:speedydeletion  -family:wikipedia "-catr:Candidates for speedy deletion"
python  ./pwb.py transferbot -lang:pl -tolang:pl -tofamily:speedydeletion  -family:wikipedia "-catr:Ekspresowe kasowanie"
python  ./pwb.py transferbot -lang:yi -tolang:yi -tofamily:speedydeletion  -family:wikipedia "-catr:געשטעלטע צו שנעל מעקן"
python  ./pwb.py transferbot -lang:fr -tolang:fr -tofamily:speedydeletion  -family:wikipedia "-catr:Wikipédia:Suppression immédiate demandée"
python  ./pwb.py transferbot -lang:bo -tolang:bo -tofamily:speedydeletion  -family:wikipedia "-catr:Candidates for speedy deletion"
python  ./pwb.py transferbot -lang:ceb -tolang:ceb -tofamily:speedydeletion  -family:wikipedia "-catr:Kandidato sa pagtangtang dayon"
python  ./pwb.py transferbot -lang:yo -tolang:yo -tofamily:speedydeletion  -family:wikipedia "-catr:Àwọn ojúewé fún ìparẹ́ kíákíá"
python  ./pwb.py transferbot -lang:hr -tolang:hr -tofamily:speedydeletion  -family:wikipedia "-catr:Predlošci za neodgovarajući sadržaj"
python  ./pwb.py transferbot -lang:jv -tolang:jv -tofamily:speedydeletion  -family:wikipedia "-catr:Artikel sing layak dibusak"
python  ./pwb.py transferbot -lang:de -tolang:de -tofamily:speedydeletion  -family:wikipedia "-catr:Wikipedia:Schnelllöschen"
python  ./pwb.py transferbot -lang:fa -tolang:fa -tofamily:speedydeletion  -family:wikipedia "-catr:مقاله‌های نامزد حذف سریع"
python  ./pwb.py transferbot -lang:hi -tolang:hi -tofamily:speedydeletion  -family:wikipedia "-catr:शीघ्र हटाने योग्य पृष्ठ"
python  ./pwb.py transferbot -lang:arz -tolang:arz -tofamily:speedydeletion  -family:wikipedia "-catr:صفحات للمسح السريع"
python  ./pwb.py transferbot -lang:tg -tolang:tg -tofamily:speedydeletion  -family:wikipedia "-catr:Мақолаҳои номзади ҳазф"
python  ./pwb.py transferbot -lang:fi -tolang:fi -tofamily:speedydeletion  -family:wikipedia "-catr:Pikapoisto"
python  ./pwb.py transferbot -lang:ja -tolang:ja -tofamily:speedydeletion  -family:wikipedia "-catr:即時削除対象のページ"
python  ./pwb.py transferbot -lang:ml -tolang:ml -tofamily:speedydeletion  -family:wikipedia "-catr:പെട്ടെന്ന് നീക്കം ചെയ്യുവാൻ സാധ്യതയുള്ളവ \(എല്ലാം\)"
python  ./pwb.py transferbot -lang:scn -tolang:scn -tofamily:speedydeletion  -family:wikipedia "-catr:Pruposti pi eliminazzioni lesta"
python  ./pwb.py transferbot -lang:bn -tolang:bn -tofamily:speedydeletion  -family:wikipedia "-catr:দ্রুত অপসারণের যোগ্য"
python  ./pwb.py transferbot -lang:sr -tolang:sr -tofamily:speedydeletion  -family:wikipedia "-catr:Брзо брисање"
python  ./pwb.py transferbot -lang:sw -tolang:sw -tofamily:speedydeletion  -family:wikipedia "-catr:Makala kwa ufutaji"
python  ./pwb.py transferbot -lang:sv -tolang:sv -tofamily:speedydeletion  -family:wikipedia "-catr:Snabbraderingar"
python  ./pwb.py transferbot -lang:ur -tolang:ur -tofamily:speedydeletion  -family:wikipedia "-catr:امیدوار براۓ حذف شدگی"
python  ./pwb.py transferbot -lang:si -tolang:si -tofamily:speedydeletion  -family:wikipedia "-catr:Candidates for speedy deletion"
python  ./pwb.py transferbot -lang:gd -tolang:gd -tofamily:speedydeletion  -family:wikipedia "-catr:Candidates for speedy deletion"
python  ./pwb.py transferbot -lang:uk -tolang:uk -tofamily:speedydeletion  -family:wikipedia "-catr:Статті до швидкого вилучення"
python  ./pwb.py transferbot -lang:sl -tolang:sl -tofamily:speedydeletion  -family:wikipedia "-catr:Predlogi za hitro brisanje"
python  ./pwb.py transferbot -lang:sd -tolang:sd -tofamily:speedydeletion  -family:wikipedia "-catr:ترت ڊاٺ جا اميدوار"
python  ./pwb.py transferbot -lang:es -tolang:es -tofamily:speedydeletion  -family:wikipedia "-catr:Wikipedia:Propuestas de borrado"
python  ./pwb.py transferbot -lang:ru -tolang:ru -tofamily:speedydeletion  -family:wikipedia "-catr:Википедия:Страницы к удалению"
python  ./pwb.py transferbot -lang:pt -tolang:pt -tofamily:speedydeletion  -family:wikipedia "-catr:!Páginas para eliminação semirrápida"
python  ./pwb.py transferbot -lang:sah -tolang:sah -tofamily:speedydeletion  -family:wikipedia "-catr:Бикипиэдьийэ:Сотуллуохтаах сирэйдэр"
python  ./pwb.py transferbot -lang:fa -tolang:fa -tofamily:speedydeletion  -family:wikipedia "-catr:صفحه‌های حذف زمان‌دار"
python  ./pwb.py transferbot -lang:ja -tolang:ja -tofamily:speedydeletion  -family:wikipedia "-catr:提案削除"
python  ./pwb.py transferbot -lang:ur -tolang:ur -tofamily:speedydeletion  -family:wikipedia "-catr:مجوزہ حذف شدگیاں"
python  ./pwb.py transferbot -lang:zh -tolang:zh -tofamily:speedydeletion  -family:wikipedia "-catr:维基百科删除"
python  ./pwb.py transferbot -lang:vi -tolang:vi -tofamily:speedydeletion  -family:wikipedia "-catr:Có người đề nghị xóa đi"
python  ./pwb.py transferbot -lang:ca -tolang:ca -tofamily:speedydeletion  -family:wikipedia "-catr:Esborrar pàgines"
python  ./pwb.py transferbot -lang:it -tolang:it -tofamily:speedydeletion  -family:wikipedia "-catr:Cancellazioni"
python  ./pwb.py transferbot -lang:lb -tolang:lb -tofamily:speedydeletion  -family:wikipedia "-catr:Läschen"
python  ./pwb.py transferbot -lang:ar -tolang:ar -tofamily:speedydeletion  -family:wikipedia "-catr:حذف ويكيبيديا"
python  ./pwb.py transferbot -lang:es -tolang:es -tofamily:speedydeletion  -family:wikipedia "-catr:Wikipedia:Borrar"
python  ./pwb.py transferbot -lang:ru -tolang:ru -tofamily:speedydeletion  -family:wikipedia "-catr:Википедия:Удаление страниц"
python  ./pwb.py transferbot -lang:nl -tolang:nl -tofamily:speedydeletion  -family:wikipedia "-catr:Wikipedia:Weg"
python  ./pwb.py transferbot -lang:tl -tolang:tl -tofamily:speedydeletion  -family:wikipedia "-catr:Wikipedia deletion"
python  ./pwb.py transferbot -lang:sa -tolang:sa -tofamily:speedydeletion  -family:wikipedia "-catr:Delete"
python  ./pwb.py transferbot -lang:fo -tolang:fo -tofamily:speedydeletion  -family:wikipedia "-catr:Strikingarboð"
python  ./pwb.py transferbot -lang:yi -tolang:yi -tofamily:speedydeletion  -family:wikipedia "-catr:וויקיפעדיע אויסמעקן"
python  ./pwb.py transferbot -lang:fr -tolang:fr -tofamily:speedydeletion  -family:wikipedia "-catr:Wikipédia:Suppression"
python  ./pwb.py transferbot -lang:fa -tolang:fa -tofamily:speedydeletion  -family:wikipedia "-catr:حذف از ویکی‌پدیا"
python  ./pwb.py transferbot -lang:fi -tolang:fi -tofamily:speedydeletion  -family:wikipedia "-catr:Poistettavat"
python  ./pwb.py transferbot -lang:ja -tolang:ja -tofamily:speedydeletion  -family:wikipedia "-catr:削除関連"
python  ./pwb.py transferbot -lang:bn -tolang:bn -tofamily:speedydeletion  -family:wikipedia "-catr:উইকিপিডিয়া অপসারণ"
python  ./pwb.py transferbot -lang:sv -tolang:sv -tofamily:speedydeletion  -family:wikipedia "-catr:Wikipedia:Raderingar"
python  ./pwb.py transferbot -lang:ur -tolang:ur -tofamily:speedydeletion  -family:wikipedia "-catr:ویکیپیڈیا حذف شدگی"
python  ./pwb.py transferbot -lang:si -tolang:si -tofamily:speedydeletion  -family:wikipedia "-catr:Delete"
python  ./pwb.py transferbot -lang:so -tolang:so -tofamily:speedydeletion  -family:wikipedia "-catr:Delete"
python  ./pwb.py transferbot -lang:uk -tolang:uk -tofamily:speedydeletion  -family:wikipedia "-catr:Вікіпедія:Вилучення сторінок"
python  ./pwb.py transferbot -lang:ky -tolang:ky -tofamily:speedydeletion  -family:wikipedia "-catr:Deletion"
python  ./pwb.py transferbot -lang:my -tolang:my -tofamily:speedydeletion  -family:wikipedia "-catr:Deleteme"
